/**
 * Layout Component
 *
 * Main layout orchestrator for the application.
 * This component is generated by `hai3 scaffold layout`.
 * Uses @hai3/uikit for UI components.
 */

import React, { useEffect } from 'react';
import { useAppDispatch } from '@hai3/react';
import { Header } from './Header';
import { Footer } from './Footer';
import { Menu } from './Menu';
import { Sidebar } from './Sidebar';
import { Screen } from './Screen';
import { Popup } from './Popup';
import { Overlay } from './Overlay';

export interface LayoutProps {
  children?: React.ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    // Bootstrap application on mount
    // Add theme initialization or other startup logic here
  }, [dispatch]);

  return (
    <div className="flex flex-col h-screen w-screen overflow-hidden">
      {/* Top row: Menu + Header + Content + Sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Menu - full height on left */}
        <Menu />

        {/* Right side: Header + Content */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Header */}
          <Header />

          {/* Main content area */}
          <div className="flex flex-1 overflow-hidden">
            {/* Main content */}
            <Screen>{children}</Screen>

            {/* Sidebar */}
            <Sidebar />
          </div>
        </div>
      </div>

      {/* Footer - full width */}
      <Footer />

      {/* Popups */}
      <Popup />

      {/* Overlay */}
      <Overlay />
    </div>
  );
};

Layout.displayName = 'Layout';
